apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-app.name" . }}
  labels:
    {{ include "echo-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "echo-app.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "echo-app.name" . }}
    spec:
      restartPolicy: {{ .Values.pod_spec.restartPolicy }}
      terminationGracePeriodSeconds: {{ .Values.pod_spec.terminationGracePeriodSeconds }}
      containers:
        - name: {{ include "echo-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      {{ with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
      {{ end }}
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "echo-app.name" . }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: {{ .Values.affinity.podAntiAffinity.topologyKey }}
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "echo-app.name" . }}
